-- L'Art de la Vie POS - Supabase/PostgreSQL schema
-- Ejecutar en Supabase SQL Editor o con: supabase db push

create extension if not exists pgcrypto;

create type public.product_category as enum ('Decoración', 'Perfumes', 'Carteras', 'Varios');
create type public.payment_method as enum ('efectivo', 'tarjeta', 'transferencia');
create type public.inventory_movement_type as enum ('entrada', 'salida', 'venta');
create type public.store_role as enum ('owner', 'admin', 'cashier');

create table public.stores (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(trim(name)) between 1 and 120),
  currency char(3) not null default 'HNL',
  timezone text not null default 'America/Tegucigalpa',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.store_members (
  store_id uuid not null references public.stores(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.store_role not null default 'cashier',
  created_at timestamptz not null default now(),
  primary key (store_id, user_id)
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  code text not null check (length(trim(code)) between 1 and 50),
  name text not null check (length(trim(name)) between 1 and 160),
  category public.product_category not null,
  price numeric(12,2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  min_stock integer not null default 0 check (min_stock >= 0),
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, code)
);

create table public.sales (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete restrict,
  folio bigint generated by default as identity,
  sold_by uuid references auth.users(id) on delete set null,
  subtotal numeric(12,2) not null check (subtotal >= 0),
  discount numeric(12,2) not null default 0 check (discount >= 0 and discount <= subtotal),
  total numeric(12,2) not null check (total >= 0 and total = subtotal - discount),
  payment_method public.payment_method not null,
  cash_received numeric(12,2),
  change_amount numeric(12,2),
  created_at timestamptz not null default now(),
  constraint valid_cash_payment check (
    (payment_method = 'efectivo' and cash_received is not null and cash_received >= total and change_amount = cash_received - total)
    or (payment_method <> 'efectivo' and cash_received is null and change_amount is null)
  ),
  unique (store_id, folio)
);

create table public.sale_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  subtotal numeric(12,2) generated always as (quantity * unit_price) stored,
  unique (sale_id, product_id)
);

create table public.inventory_movements (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  sale_id uuid references public.sales(id) on delete restrict,
  created_by uuid references auth.users(id) on delete set null,
  type public.inventory_movement_type not null,
  quantity integer not null check (quantity > 0),
  product_name text not null,
  note text,
  created_at timestamptz not null default now(),
  constraint sale_movement_reference check (
    (type = 'venta' and sale_id is not null) or (type <> 'venta' and sale_id is null)
  )
);

create table public.expenses (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  created_by uuid references auth.users(id) on delete set null,
  description text not null check (length(trim(description)) between 1 and 300),
  amount numeric(12,2) not null check (amount > 0),
  created_at timestamptz not null default now()
);

create table public.cash_closes (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete restrict,
  business_date date not null,
  closed_by uuid references auth.users(id) on delete set null,
  total_sales numeric(12,2) not null check (total_sales >= 0),
  cash_sales numeric(12,2) not null check (cash_sales >= 0),
  card_sales numeric(12,2) not null check (card_sales >= 0),
  transfer_sales numeric(12,2) not null check (transfer_sales >= 0),
  total_expenses numeric(12,2) not null check (total_expenses >= 0),
  expected_cash numeric(12,2) not null,
  actual_cash numeric(12,2) not null check (actual_cash >= 0),
  difference numeric(12,2) generated always as (actual_cash - expected_cash) stored,
  created_at timestamptz not null default now(),
  unique (store_id, business_date)
);

create table public.cash_close_expenses (
  cash_close_id uuid not null references public.cash_closes(id) on delete cascade,
  expense_id uuid not null references public.expenses(id) on delete restrict,
  primary key (cash_close_id, expense_id),
  unique (expense_id)
);

create index products_store_active_idx on public.products (store_id, active);
create index products_store_category_idx on public.products (store_id, category);
create index sales_store_created_idx on public.sales (store_id, created_at desc);
create index sale_items_sale_idx on public.sale_items (sale_id);
create index sale_items_product_idx on public.sale_items (product_id);
create index movements_store_created_idx on public.inventory_movements (store_id, created_at desc);
create index movements_product_idx on public.inventory_movements (product_id, created_at desc);
create index expenses_store_created_idx on public.expenses (store_id, created_at desc);
create index cash_closes_store_date_idx on public.cash_closes (store_id, business_date desc);
create index store_members_user_idx on public.store_members (user_id, store_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger stores_set_updated_at before update on public.stores
for each row execute function public.set_updated_at();
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
create trigger products_set_updated_at before update on public.products
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.email));
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_store_member(requested_store_id uuid)
returns boolean
language sql
stable
security definer set search_path = ''
as $$
  select exists (
    select 1 from public.store_members
    where store_id = requested_store_id and user_id = (select auth.uid())
  );
$$;

create or replace function public.can_manage_store(requested_store_id uuid)
returns boolean
language sql
stable
security definer set search_path = ''
as $$
  select exists (
    select 1 from public.store_members
    where store_id = requested_store_id
      and user_id = (select auth.uid())
      and role in ('owner', 'admin')
  );
$$;

-- Registra entradas/salidas y cambia stock dentro de la misma transacción.
create or replace function public.register_inventory_movement(
  requested_store_id uuid,
  requested_product_id uuid,
  movement_type public.inventory_movement_type,
  movement_quantity integer,
  movement_note text default null
)
returns public.inventory_movements
language plpgsql
security invoker
set search_path = ''
as $$
declare
  selected_product public.products;
  created_movement public.inventory_movements;
begin
  if movement_type not in ('entrada', 'salida') then
    raise exception 'Solo se permiten movimientos de entrada o salida';
  end if;
  if movement_quantity <= 0 then raise exception 'La cantidad debe ser positiva'; end if;

  select * into selected_product from public.products
  where id = requested_product_id and store_id = requested_store_id and active
  for update;
  if not found then raise exception 'Producto no encontrado'; end if;
  if movement_type = 'salida' and selected_product.stock < movement_quantity then
    raise exception 'Stock insuficiente para %', selected_product.name;
  end if;

  update public.products set stock = stock + case when movement_type = 'entrada' then movement_quantity else -movement_quantity end
  where id = requested_product_id;
  insert into public.inventory_movements (store_id, product_id, created_by, type, quantity, product_name, note)
  values (requested_store_id, requested_product_id, (select auth.uid()), movement_type, movement_quantity, selected_product.name, nullif(trim(movement_note), ''))
  returning * into created_movement;
  return created_movement;
end;
$$;

-- El servidor envía [{"productId":"uuid","quantity":2}]. Precios y stock se resuelven aquí.
create or replace function public.complete_sale(
  requested_store_id uuid,
  requested_items jsonb,
  requested_payment_method public.payment_method,
  discount_percent numeric default 0,
  requested_cash_received numeric default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  requested_item jsonb;
  selected_product public.products;
  item_quantity integer;
  calculated_subtotal numeric(12,2) := 0;
  calculated_discount numeric(12,2);
  calculated_total numeric(12,2);
  calculated_change numeric(12,2);
  created_sale public.sales;
begin
  if jsonb_typeof(requested_items) <> 'array' or jsonb_array_length(requested_items) = 0 then
    raise exception 'La venta no contiene productos';
  end if;
  if discount_percent < 0 or discount_percent > 100 then raise exception 'Descuento inválido'; end if;

  for requested_item in select * from jsonb_array_elements(requested_items)
  loop
    item_quantity := (requested_item ->> 'quantity')::integer;
    if item_quantity <= 0 then raise exception 'Cantidad inválida'; end if;
    select * into selected_product from public.products
    where id = (requested_item ->> 'productId')::uuid and store_id = requested_store_id and active
    for update;
    if not found then raise exception 'Producto no encontrado'; end if;
    if selected_product.stock < item_quantity then raise exception 'Stock insuficiente para %', selected_product.name; end if;
    calculated_subtotal := calculated_subtotal + selected_product.price * item_quantity;
  end loop;

  calculated_discount := round(calculated_subtotal * discount_percent / 100, 2);
  calculated_total := calculated_subtotal - calculated_discount;
  if requested_payment_method = 'efectivo' then
    if requested_cash_received is null or requested_cash_received < calculated_total then raise exception 'Efectivo insuficiente'; end if;
    calculated_change := requested_cash_received - calculated_total;
  elsif requested_cash_received is not null then
    raise exception 'cash_received solo aplica a efectivo';
  end if;

  insert into public.sales (store_id, sold_by, subtotal, discount, total, payment_method, cash_received, change_amount)
  values (requested_store_id, (select auth.uid()), calculated_subtotal, calculated_discount, calculated_total,
          requested_payment_method, requested_cash_received, calculated_change)
  returning * into created_sale;

  for requested_item in select * from jsonb_array_elements(requested_items)
  loop
    item_quantity := (requested_item ->> 'quantity')::integer;
    select * into selected_product from public.products where id = (requested_item ->> 'productId')::uuid for update;
    insert into public.sale_items (sale_id, product_id, product_name, quantity, unit_price)
    values (created_sale.id, selected_product.id, selected_product.name, item_quantity, selected_product.price);
    update public.products set stock = stock - item_quantity where id = selected_product.id;
    insert into public.inventory_movements (store_id, product_id, sale_id, created_by, type, quantity, product_name)
    values (requested_store_id, selected_product.id, created_sale.id, (select auth.uid()), 'venta', item_quantity, selected_product.name);
  end loop;

  return jsonb_build_object('id', created_sale.id, 'folio', created_sale.folio, 'subtotal', created_sale.subtotal,
    'discount', created_sale.discount, 'total', created_sale.total, 'paymentMethod', created_sale.payment_method,
    'cashReceived', created_sale.cash_received, 'change', created_sale.change_amount, 'date', created_sale.created_at);
end;
$$;

create or replace function public.close_cash(requested_store_id uuid, requested_actual_cash numeric)
returns public.cash_closes
language plpgsql
security invoker
set search_path = ''
as $$
declare
  local_date date;
  cash_total numeric(12,2);
  card_total numeric(12,2);
  transfer_total numeric(12,2);
  expenses_total numeric(12,2);
  created_close public.cash_closes;
begin
  if requested_actual_cash < 0 then raise exception 'El efectivo real no puede ser negativo'; end if;
  select (now() at time zone timezone)::date into local_date from public.stores where id = requested_store_id;
  if local_date is null then raise exception 'Tienda no encontrada'; end if;

  select
    coalesce(sum(total) filter (where payment_method = 'efectivo'), 0),
    coalesce(sum(total) filter (where payment_method = 'tarjeta'), 0),
    coalesce(sum(total) filter (where payment_method = 'transferencia'), 0)
  into cash_total, card_total, transfer_total
  from public.sales
  where store_id = requested_store_id and (created_at at time zone (select timezone from public.stores where id = requested_store_id))::date = local_date;

  select coalesce(sum(e.amount), 0) into expenses_total
  from public.expenses e
  left join public.cash_close_expenses cce on cce.expense_id = e.id
  where e.store_id = requested_store_id and cce.expense_id is null
    and (e.created_at at time zone (select timezone from public.stores where id = requested_store_id))::date = local_date;

  insert into public.cash_closes (store_id, business_date, closed_by, total_sales, cash_sales, card_sales,
    transfer_sales, total_expenses, expected_cash, actual_cash)
  values (requested_store_id, local_date, (select auth.uid()), cash_total + card_total + transfer_total,
    cash_total, card_total, transfer_total, expenses_total, cash_total - expenses_total, requested_actual_cash)
  returning * into created_close;

  insert into public.cash_close_expenses (cash_close_id, expense_id)
  select created_close.id, e.id from public.expenses e
  left join public.cash_close_expenses cce on cce.expense_id = e.id
  where e.store_id = requested_store_id and cce.expense_id is null
    and (e.created_at at time zone (select timezone from public.stores where id = requested_store_id))::date = local_date;
  return created_close;
end;
$$;

-- RLS: la API con service_role puede administrar; usuarios autenticados solo sus tiendas.
alter table public.stores enable row level security;
alter table public.profiles enable row level security;
alter table public.store_members enable row level security;
alter table public.products enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.expenses enable row level security;
alter table public.cash_closes enable row level security;
alter table public.cash_close_expenses enable row level security;

create policy "members read stores" on public.stores for select to authenticated using (public.is_store_member(id));
create policy "users read own profile" on public.profiles for select to authenticated using (id = (select auth.uid()));
create policy "users update own profile" on public.profiles for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));
create policy "members read memberships" on public.store_members for select to authenticated using (public.is_store_member(store_id));
create policy "members read products" on public.products for select to authenticated using (public.is_store_member(store_id));
create policy "managers insert products" on public.products for insert to authenticated with check (public.can_manage_store(store_id));
create policy "managers update products" on public.products for update to authenticated using (public.can_manage_store(store_id)) with check (public.can_manage_store(store_id));
create policy "managers delete products" on public.products for delete to authenticated using (public.can_manage_store(store_id));
create policy "members read sales" on public.sales for select to authenticated using (public.is_store_member(store_id));
create policy "members create sales" on public.sales for insert to authenticated with check (public.is_store_member(store_id));
create policy "members read sale items" on public.sale_items for select to authenticated using (
  exists (select 1 from public.sales s where s.id = sale_id and public.is_store_member(s.store_id))
);
create policy "members create sale items" on public.sale_items for insert to authenticated with check (
  exists (select 1 from public.sales s where s.id = sale_id and public.is_store_member(s.store_id))
);
create policy "members read movements" on public.inventory_movements for select to authenticated using (public.is_store_member(store_id));
create policy "members create movements" on public.inventory_movements for insert to authenticated with check (public.is_store_member(store_id));
create policy "members read expenses" on public.expenses for select to authenticated using (public.is_store_member(store_id));
create policy "members create expenses" on public.expenses for insert to authenticated with check (public.is_store_member(store_id));
create policy "members read cash closes" on public.cash_closes for select to authenticated using (public.is_store_member(store_id));
create policy "members create cash closes" on public.cash_closes for insert to authenticated with check (public.is_store_member(store_id));
create policy "members read closed expenses" on public.cash_close_expenses for select to authenticated using (
  exists (select 1 from public.cash_closes c where c.id = cash_close_id and public.is_store_member(c.store_id))
);
create policy "members link closed expenses" on public.cash_close_expenses for insert to authenticated with check (
  exists (select 1 from public.cash_closes c where c.id = cash_close_id and public.is_store_member(c.store_id))
);

grant usage on schema public to authenticated, service_role;
grant select, insert, update, delete on all tables in schema public to authenticated, service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;
grant execute on function public.register_inventory_movement(uuid, uuid, public.inventory_movement_type, integer, text) to authenticated, service_role;
grant execute on function public.complete_sale(uuid, jsonb, public.payment_method, numeric, numeric) to authenticated, service_role;
grant execute on function public.close_cash(uuid, numeric) to authenticated, service_role;

-- Tienda y catálogo inicial. Conserva este UUID en SUPABASE_STORE_ID del backend.
insert into public.stores (id, name) values ('00000000-0000-0000-0000-000000000001', 'L''Art de la Vie');
insert into public.products (store_id, code, name, category, price, stock, min_stock) values
('00000000-0000-0000-0000-000000000001', 'DEC-001', 'Jarrón Cerámico Artesanal', 'Decoración', 85, 12, 3),
('00000000-0000-0000-0000-000000000001', 'DEC-002', 'Portavelas Dorado Set x3', 'Decoración', 45, 8, 5),
('00000000-0000-0000-0000-000000000001', 'DEC-003', 'Espejo Marco Tallado', 'Decoración', 220, 2, 3),
('00000000-0000-0000-0000-000000000001', 'PER-001', 'Eau de Parfum Rose Noir', 'Perfumes', 150, 15, 5),
('00000000-0000-0000-0000-000000000001', 'PER-002', 'Difusor Ambiental Lavanda', 'Perfumes', 35, 20, 8),
('00000000-0000-0000-0000-000000000001', 'PER-003', 'Vela Aromática Sándalo', 'Perfumes', 28, 1, 5),
('00000000-0000-0000-0000-000000000001', 'CAR-001', 'Cartera Cuero Italiano', 'Carteras', 320, 6, 2),
('00000000-0000-0000-0000-000000000001', 'CAR-002', 'Clutch Fiesta Dorado', 'Carteras', 95, 10, 3),
('00000000-0000-0000-0000-000000000001', 'VAR-001', 'Set de Té Porcelana', 'Varios', 75, 4, 2),
('00000000-0000-0000-0000-000000000001', 'VAR-002', 'Caja Musical Vintage', 'Varios', 60, 7, 3);
